### ISSUE TITLE
smartparens-strict-mode  breaks hungry-delete-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [nflath/hungry-delete#21]
Looks like if i've `smartparens-strict-mode` enabled,  `hungry-delete-mode` will stop working. I use emacs 25.1 on a mac.

**Comment by nflath** [comment]
I looked into this; I think it's more an issue in smartparens-strict-mode, I'm not entirely sure how to fix it in hungry-delete.  The problem is smarparens uses sp-backward-delete-char, which in it's base case just calls delete-char -1.  I *think* this would have to be a change in that package - if there are any other ways of fixing this you see please let me know.

**Comment by CSRaghunandan** [comment]
I asked the same question today in emacs.SE and Glucas wrote an [answer](http://emacs.stackexchange.com/a/29484/12247) which fixes `hungry-delete-mode` when `smartparens-strict-mode` is enabled.
